### ISSUE TITLE
not an issue - question on rendering constellation lines. 

### ISSUE THREAD

**Issue by johndpope** [DJBen/StarryNight#3]
firstly, thanks so much for all your efforts here - it's an amazing library. Kudos

I threw this crude method together - and it does draw stars into scene.
my problem is getting the lines to appear as if they are in a dome - 

**cosmographia app from nasa** - https://github.com/claurel/cosmographia
<img width="1150" alt="screen shot 2018-02-20 at 11 10 51 am" src="https://user-images.githubusercontent.com/289994/36435121-c7400ed4-162e-11e8-8816-57efa157d3d9.png">
as opposed to floating around in the scene. the lines are appearing to point into the earth. 

Any suggestions? I was thinking just make all the z dimensions hard coded to a value really far away. 

```swift
    func addStars(){
        
        let stars = Star.magitudeLessThan(7)
        for star in stars{
            let scnText = TextNode(star.identity.properName ?? "")
            scnText.position = SCNVector3( star.physicalInfo.coordinate)
            constellationLines.addChildNode(scnText)
            
            let starNode = SCNNode(geometry: SCNSphere(radius: 0.01))
            starNode.geometry?.firstMaterial?.diffuse.contents = UIImage(named:"spark.png")
            starNode.position = SCNVector3( star.physicalInfo.coordinate)
            constellationLines.addChildNode(starNode)
        }
        //lines + names
        for constellation in Constellation.all{
            let scnText = TextNode(constellation.name )
            scnText.font = UIFont.systemFont(ofSize: 0.2)
            scnText.color = .red
            if let center = constellation.displayCenter{
                scnText.position = SCNVector3(center) * 10
                constellationLines.addChildNode(scnText)
            }
            
            
            for (_,line) in constellation.connectionLines.enumerated(){
                let line = SCNNode.lineNode(from: SCNVector3( line.star1.physicalInfo.coordinate), to: SCNVector3(line.star2.physicalInfo.coordinate))
                constellationLines.addChildNode(line)
            }
        }
    }
```

**Comment by johndpope** [comment]
related question - how to draw borders 

<img width="1437" alt="screen shot 2018-02-20 at 12 26 05 pm" src="https://user-images.githubusercontent.com/289994/36441282-226068fc-1640-11e8-98f7-8aa3fa7a53f9.png">

**Comment by ferreiradantas10** [comment]
hello you is a worker of stary night
